on:
  push:
    paths:
      - README.Rmd

name: Render README

jobs:
  render:
    name: Render README
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - { os: ubuntu-18.04, r: '4.0', cran: "https://packagemanager.rstudio.com/all/__linux__/bionic/latest"}
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      CRAN: ${{ matrix.config.cran }}
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.config.r }}
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ matrix.config.r }}-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-r-${{ matrix.config.r }}-
            ${{ runner.os }}-r-${{ matrix.config.r }}-libs-rcmdcheck-
      - name: Install remotes
        run: >
          Rscript
          -e "if (system.file(package = 'remotes') == '') install.packages('remotes')"
      - name: Install dependencies
        run: >
          Rscript
          -e "remotes::install_deps(dependencies = TRUE)"
          -e "remotes::install_cran('rmarkdown')"
          -e "remotes::install_cran('devtools')"
      - name: Render README
        run: >
          Rscript
          -e 'devtools::build_readme(quiet = FALSE)'
      - name: Commit results
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git commit README.md -m 'Re-build README.Rmd' || echo "No changes to commit"
          git push https://schloerke:${{secrets.GH_PAT}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to push"
